name: Auto Collect Sentences

on:
  schedule:
    - cron: "0 */6 * * *"   # 6시간마다 실행
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Ensure docs dir exists
        run: mkdir -p docs

      - name: Run crawler
        run: python docs/crawler.py

      - name: Run preprocess (sqlite → json)
        run: python docs/preprocess.py

      - name: Commit and Push updated DB + JSON
        run: |
          git config user.name "ESP Bot"
          git config user.email "espbot@example.com"
          git add docs/memory.sqlite docs/memory.json || true
          git commit -m "Auto-update memory DB+JSON [skip ci]" || echo "No changes"
          git push
