name: ops-awake
on:
  workflow_dispatch: {}
  issue_comment:
    types: [created]

jobs:
  gate:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'issue_comment' && contains(github.event.comment.body, 'Awake')) }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Awake accepted"

  vercel:
    needs: gate
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy Hook (prod)
        run: |
          test -n "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}" || (echo "missing hook" && exit 1)
          for i in 1 2 3; do
            code=$(curl -s -o /dev/null -w "%{http_code}" -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}")
            echo "HTTP $code (try $i)"
            [ "$code" = "200" ] && break
            sleep 10
          done
          [ "$code" = "200" ] || (echo "deploy hook failed" && exit 1)
      - name: Warmup
        run: sleep 30

  verify:
    needs: vercel
    runs-on: ubuntu-latest
    steps:
      - name: Probe site (tolerant)
        run: |
          for i in 1 2 3 4 5; do
            curl -fsSIL "https://espdialog.net/?nocache=$(date +%s)$i" | grep -Eiq '^HTTP/.* 200' && exit 0
            sleep 6
          done
          exit 1
