name: ops-awake
on:
  workflow_dispatch: {}
  issue_comment:
    types: [created]

jobs:
  gate:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'issue_comment' && contains(github.event.comment.body, 'Awake')) }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Awake signal accepted."

  heartbeat-commit:
    needs: gate
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Touch heartbeat (cache-busting)
        run: |
          mkdir -p .ops
          date -u +"%Y-%m-%dT%H:%M:%SZ" > .ops/heartbeat.txt
      - name: Commit & Push
        run: |
          git config user.name "ops-bot"
          git config user.email "ops-bot@users.noreply.github.com"
          git add .ops/heartbeat.txt
          git commit -m "ops: heartbeat $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "no changes"
          git push

  vercel-deploy:
    needs: heartbeat-commit
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Vercel auto-deploy
        run: sleep 20

  purge-cloudflare:
    needs: vercel-deploy
    runs-on: ubuntu-latest
    if: ${{ secrets.CF_API_TOKEN != '' && secrets.CF_ZONE_ID != '' }}
    steps:
      - name: Purge Cloudflare Cache (entire zone)
        run: |
          curl -sS -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/purge_cache" \
          -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{"purge_everything":true}'

  verify:
    needs: purge-cloudflare
    runs-on: ubuntu-latest
    steps:
      - name: Probe (retry up to 5)
        run: |
          set -e
          for i in 1 2 3 4 5; do
            curl -fsSI "https://espdialog.net/?nocache=$(date +%s)$i" | tee headers.txt || true
            grep -Eiq "cf-cache-status: (BYPASS|MISS)" headers.txt && exit 0
            sleep 5
          done
          exit 1

  report:
    needs: [verify]
    if: ${{ github.event_name == 'issue_comment' }}
    runs-on: ubuntu-latest
    steps:
      - name: Post result
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          MSG="✅ Awake: deploy+purge done at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
          gh api repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments -f body="$MSG"
