# .github/workflows/run_zip_handler.yml 파일 내용

name: Run Zip Handler One-Time

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/memory.json'
      - 'zip_handler.py'

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Python 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 필요한 라이브러리 설치 (requests 등을 포함)
      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt

      # memory.json 삭제 및 스크립트 실행
      - name: Run zip_handler.py to create 50k data
        run: |
          rm docs/memory.json
          python docs/zip_handler.py
          
      # 생성된 memory.json을 Git에 반영하기 위해 임시 커밋
      - name: Commit and Push new memory.json
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/memory.json
          git commit -m "chore: Regenerate 50k memory.json via GitHub Action"
          git push
